FROM openjdk:8-jdk-alpine
VOLUME /tmp
EXPOSE 8081
ADD ./build/libs/virusNeftal-0.0.1-SNAPSHOT.jar app.jar
ENTRYPOINT ["java","-Dspring.data.mongodb.uri=mongodb://mongodb:27017/virus","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
