apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /home/liroy/Documents/kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: angular-front
  name: angular-front
spec:
  ports:
  - name: "4200"
    port: 4200
    targetPort: 4200
  selector:
    io.kompose.service: angular-front
status:
  loadBalancer: {}
