apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /home/liroy/Documents/kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: angular-front
  name: angular-front
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: angular-front
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /home/liroy/Documents/kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: angular-front
    spec:
      containers:
      - image: angular-front
        imagePullPolicy: ""
        name: angular-front
        ports:
        - containerPort: 4200
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
