apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /home/liroy/Documents/kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: check-service
  name: check-service
spec:
  ports:
  - name: "8082"
    port: 8082
    targetPort: 8082
  selector:
    io.kompose.service: check-service
status:
  loadBalancer: {}
