apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /home/liroy/Documents/kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: check-service
  name: check-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: check-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /home/liroy/Documents/kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: check-service
    spec:
      containers:
      - env:
        - name: EUREKA_SERVER
          value: http://discovery:8761/eureka
        image: checker-service
        imagePullPolicy: ""
        name: check-service
        ports:
        - containerPort: 8082
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
