version: '3'
services:
    mongodb:
        image: mongo:3.2.4
        container_name: "mongodb"
        volumes:
            - /home/sinoed/data/db:/data/db
        ports:
            - "27017:27017"
        command: --smallfiles
    discovery:
        image: eureka-server
        ports:
            - "8761:8761"     
    virusneftal:
        image: virusneftal
        environment:
            - EUREKA_SERVER=http://discovery:8761/eureka
        depends_on:
            - mongodb
            - discovery
        ports:
            - "8081:8081"
        links:
            - mongodb
    check-service:
        image: checker-service
        environment:
            - EUREKA_SERVER=http://discovery:8761/eureka
        depends_on:
            - discovery
            - virusneftal
        ports:
            - "8082:8082"
    angular-front:
        image: angular-front
        ports:
            - "4200:4200"
            
